"""Full video-pipe teardown regression; only generated bytes and fake input."""
import argparse
import asyncio
import json
import os
from pathlib import Path
import ssl
import struct
import subprocess
import sys
import time
from input_tls import ROOT, create_pair
from input_protocol import Event


async def run(directory,fixture,port):
    directory.mkdir(parents=True,exist_ok=False)
    pair_dir=directory/'pair';create_pair(pair_dir,'127.0.0.1',port)
    pair=json.loads((pair_dir/'lab-pair.json').read_text())
    environment=dict(os.environ,SPATIAL_INPUT_FIXTURE_FLOOD='1')
    with (directory/'host.log').open('w') as log:
        host=await asyncio.create_subprocess_exec(sys.executable,str(ROOT/'windows/host/lab_server.py'),
            '--credentials',str(pair_dir),'--capture',str(fixture),'--input-bridge',str(fixture),'--enable-input',
            '--bind','127.0.0.1','--lifetime','15',stdout=log,stderr=log,env=environment,
            creationflags=subprocess.CREATE_NO_WINDOW if os.name=='nt' else 0)
        writer=None
        try:
            deadline=time.monotonic()+5
            while 'listening' not in (directory/'host.log').read_text():
                if time.monotonic()>deadline:raise RuntimeError('Flood host failed to start')
                await asyncio.sleep(.05)
            context=ssl.create_default_context(cafile=str(pair_dir/'root.pem'))
            context.minimum_version=ssl.TLSVersion.TLSv1_3;context.set_alpn_protocols(['spatialpc/1'])
            context.load_cert_chain(str(pair_dir/'client.pem'),str(pair_dir/'client-key.pem'))
            reader,writer=await asyncio.open_connection('127.0.0.1',port,ssl=context,server_hostname=pair['serverName'],limit=4096)
            payload=json.dumps(dict(version=1,codecs=['h264-annexb'],maxWidth=8192,maxHeight=8192,input={'version':1})).encode()
            writer.write(b'SPC1'+struct.pack('!I',len(payload))+payload);await writer.drain()
            header=await asyncio.wait_for(reader.readexactly(8),3)
            caps=json.loads(await reader.readexactly(struct.unpack('!I',header[4:])[0]));assert caps['input']['enabled']
            writer.write(Event(5,0,1,0,0,0).wire());writer.write(Event(4,1,2,4,0,0).wire());await writer.drain()
            admitted=time.monotonic()
            while 'fixture_control_active' not in (directory/'input-status.log').read_text():
                assert time.monotonic()-admitted<1
                await asyncio.sleep(.01)
            admitted=time.monotonic()
            # Do not consume video: fill TLS/capture pipes while the lease expires.
            summary=None
            while time.monotonic()-admitted<3:
                lines=(directory/'input-status.log').read_text().split('\n')[:-1]
                summaries=[json.loads(line.split('=',1)[1]) for line in lines if line.startswith('fixture_input_summary=')]
                if summaries:summary=summaries[-1];break
                await asyncio.sleep(.01)
            released_at=time.monotonic()-admitted
            assert summary and summary['downs']==summary['ups']==1, 'Held key did not release under full video pipe'
            async def discarded_eof():
                try:
                    while await reader.read(65536):pass
                except ConnectionError:pass
            await asyncio.wait_for(discarded_eof(),1.5)
            closed_at=time.monotonic()-admitted
            assert closed_at<4.5
            # Server cleanup must finish as well; EOF alone does not prove reaping.
            deadline=time.monotonic()+4.5
            while 'input_summary=' not in (directory/'host.log').read_text() or 'transport_summary=' not in (directory/'host.log').read_text():
                assert time.monotonic()<deadline,'Child cleanup did not finish'
                await asyncio.sleep(.01)
            result=dict(fixtureOnly=True,desktopCapture=False,inputInjection=False,
                        releaseAfterAdmissionSeconds=released_at,sessionClosedAfterAdmissionSeconds=closed_at,
                        nativeRelease=summary,fullVideoPipeCleanup=True)
            (directory/'result.json').write_text(json.dumps(result,indent=2)+'\n')
            print(json.dumps(result))
        finally:
            if writer:writer.transport.abort()
            if host.returncode is None:host.terminate()
            await host.wait()


if __name__=='__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('--directory',type=Path,required=True)
    parser.add_argument('--fixture',type=Path,required=True)
    parser.add_argument('--port',type=int,default=47994)
    args=parser.parse_args()
    asyncio.run(run(args.directory.resolve(),args.fixture.resolve(),args.port))
